"""Initial SQLite schema

Revision ID: 12d214e3548e
Revises: 
Create Date: 2026-09-13 23:29:43.084550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d214e3548e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_change_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_change_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_change_history_config_entity'), ['config_entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_change_history_entity_id'), ['entity_id'], unique=False)

    op.create_table('escalation_matrix',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('threshold_hours_after_breach', sa.Integer(), nullable=False),
    sa.Column('recipient_role_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalation_matrix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalation_matrix_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalation_matrix_lob_id'), ['lob_id'], unique=False)

    op.create_table('evidence_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('error_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('malware_scan_status', sa.String(length=20), nullable=False),
    sa.Column('is_current_version', sa.Boolean(), nullable=False),
    sa.Column('supersedes_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("malware_scan_status IN ('PENDING', 'CLEAN', 'INFECTED', 'FAILED')", name='chk_malware_status'),
    sa.CheckConstraint("stage IN ('ORIGINAL_LOGGING', 'REBUTTAL', 'DECISION')", name='chk_evidence_stage'),
    sa.ForeignKeyConstraint(['supersedes_evidence_id'], ['evidence_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_files_error_id'), ['error_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_files_local_id'), ['local_id'], unique=True)

    op.create_table('evidence_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('max_file_count_per_error', sa.Integer(), nullable=False),
    sa.Column('allowed_file_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_region_code'), ['region_code'], unique=False)

    op.create_table('in_app_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('error_id', sa.String(length=36), nullable=True),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_in_app_notifications_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_in_app_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('lobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lobs_code'), ['code'], unique=True)

    op.create_table('notification_templates',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ownership_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('default_owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('default_owner_team_ref', sa.Uuid(), nullable=True),
    sa.Column('default_owner_manager_user_id', sa.Uuid(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ownership_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ownership_mapping_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_mapping_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_ownership_mapping_lob_id'), ['lob_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('qa_error_id_sequences',
    sa.Column('lob_year_key', sa.String(), nullable=False),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('lob_year_key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sla_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('rebuttal_window_hours', sa.Integer(), nullable=False),
    sa.Column('decision_window_hours', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sla_rules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_rules_effective_to'), ['effective_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_rules_lob_id'), ['lob_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sla_rules_severity'), ['severity'], unique=False)

    op.create_table('sync_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('working_hours_calendar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('business_start_time', sa.Time(), nullable=False),
    sa.Column('business_end_time', sa.Time(), nullable=False),
    sa.Column('business_days_of_week', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('working_hours_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_working_hours_calendar_region_code'), ['region_code'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_evidence_at_severity', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lob_id', 'name', name='uix_category_lob_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_lob_id'), ['lob_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_access_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('accessed_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("action IN ('VIEW', 'DOWNLOAD')", name='chk_access_action'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.String(length=36), nullable=True),
    sa.Column('template_code', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'SENT', 'DELIVERED', 'BOUNCED', 'FAILED')", name='chk_notif_status'),
    sa.ForeignKeyConstraint(['template_code'], ['notification_templates.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uix_subcategory_category_name')
    )
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_categories_category_id'), ['category_id'], unique=False)

    op.create_table('sync_cursor',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('last_pulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pushed_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('qa_error_id', sa.String(), nullable=False),
    sa.Column('lob_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('sub_category_id', sa.Uuid(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=False),
    sa.Column('logged_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('date_of_occurrence', sa.Date(), nullable=False),
    sa.Column('date_of_detection', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_root_cause', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('client_impact_flag', sa.Boolean(), nullable=False),
    sa.Column('sla_rebuttal_window_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('sla_decision_window_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('sla_clock_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_escalation_level', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name='chk_severity'),
    sa.CheckConstraint('char_length(description) >= 20', name='chk_description_length'),
    sa.CheckConstraint('date_of_occurrence <= CURRENT_DATE', name='chk_date_occurrence'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.create_index('idx_errors_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_errors_lob_category', ['lob_id', 'category_id'], unique=False)
        batch_op.create_index('idx_errors_owner_user_id', ['owner_user_id'], unique=False)
        batch_op.create_index('idx_errors_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_errors_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_errors_qa_error_id'), ['qa_error_id'], unique=True)

    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('error_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('partial_breakdown', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision IN ('UPHELD','OVERTURNED','PARTIALLY_UPHELD')", name='decision_enum'),
    sa.CheckConstraint('length(rationale) >= 20', name='rationale_min_length'),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_local_id'), ['local_id'], unique=True)

    op.create_table('error_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('performed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('performed_by_system', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_status_history_error_id'), ['error_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_status_history_local_id'), ['local_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_error_status_history_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('rebuttals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('error_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('evidence_file_ids', sa.JSON(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('local_id', sa.Uuid(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('updated_by_device_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(justification) >= 20', name='justification_min_length'),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rebuttals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rebuttals_local_id'), ['local_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rebuttals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rebuttals_local_id'))

    op.drop_table('rebuttals')
    with op.batch_alter_table('error_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_status_history_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_error_status_history_local_id'))
        batch_op.drop_index(batch_op.f('ix_error_status_history_error_id'))

    op.drop_table('error_status_history')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_local_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_errors_qa_error_id'))
        batch_op.drop_index(batch_op.f('ix_errors_local_id'))
        batch_op.drop_index('idx_errors_status')
        batch_op.drop_index('idx_errors_owner_user_id')
        batch_op.drop_index('idx_errors_lob_category')
        batch_op.drop_index('idx_errors_created_at')

    op.drop_table('errors')
    op.drop_table('sync_cursor')
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_categories_category_id'))

    op.drop_table('sub_categories')
    op.drop_table('user_roles')
    op.drop_table('notifications_log')
    op.drop_table('evidence_access_log')
    op.drop_table('devices')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_lob_id'))

    op.drop_table('categories')
    with op.batch_alter_table('working_hours_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_working_hours_calendar_region_code'))

    op.drop_table('working_hours_calendar')
    op.drop_table('users')
    op.drop_table('sync_queue')
    with op.batch_alter_table('sla_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sla_rules_severity'))
        batch_op.drop_index(batch_op.f('ix_sla_rules_lob_id'))
        batch_op.drop_index(batch_op.f('ix_sla_rules_effective_to'))
        batch_op.drop_index(batch_op.f('ix_sla_rules_category_id'))

    op.drop_table('sla_rules')
    op.drop_table('roles')
    op.drop_table('qa_error_id_sequences')
    op.drop_table('projects')
    with op.batch_alter_table('ownership_mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownership_mapping_lob_id'))
        batch_op.drop_index(batch_op.f('ix_ownership_mapping_effective_to'))
        batch_op.drop_index(batch_op.f('ix_ownership_mapping_category_id'))

    op.drop_table('ownership_mapping')
    op.drop_table('notification_templates')
    with op.batch_alter_table('lobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lobs_code'))

    op.drop_table('lobs')
    with op.batch_alter_table('in_app_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_in_app_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_in_app_notifications_local_id'))

    op.drop_table('in_app_notifications')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_region_code'))

    op.drop_table('holidays')
    op.drop_table('evidence_rules')
    with op.batch_alter_table('evidence_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_files_local_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_files_error_id'))

    op.drop_table('evidence_files')
    with op.batch_alter_table('escalation_matrix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalation_matrix_lob_id'))
        batch_op.drop_index(batch_op.f('ix_escalation_matrix_is_active'))

    op.drop_table('escalation_matrix')
    with op.batch_alter_table('config_change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_change_history_entity_id'))
        batch_op.drop_index(batch_op.f('ix_config_change_history_config_entity'))
        batch_op.drop_index(batch_op.f('ix_config_change_history_changed_at'))

    op.drop_table('config_change_history')
    # ### end Alembic commands ###
