<#
.SYNOPSIS
Automates the Azure AD Application Registration for QEMS Microsoft Integrations (Teams Bot & Outlook Webhooks).

.DESCRIPTION
This script uses the Azure CLI to:
1. Create a new Azure AD Application Registration named "QEMS Integrations".
2. Assign the required Microsoft Graph API Application permissions:
   - Mail.Send (for sending Outlook notifications)
   - Mail.Read (for reading reply threads)
   - Chat.ReadWrite (for the Teams bot)
   - ChannelMessage.Send (for the Teams bot)
3. Assign the delegated User.Read permission.
4. Generate a Client Secret.

.PREREQUISITES
- Azure CLI (az) must be installed.
- You must run `az login` with an account that has Application Administrator or Global Administrator privileges in your tenant.

.NOTES
After running this script, you still need to manually create an "Azure Bot" resource in the Azure Portal
and link it to the App ID generated by this script.
#>

$AppName = "QEMS-Integrations-Bot"
$GraphResourceAppId = "00000003-0000-0000-c000-000000000000" # Microsoft Graph

Write-Host "Checking Azure CLI login status..."
$account = az account show | ConvertFrom-Json
if (-not $account) {
    Write-Error "Not logged into Azure CLI. Please run 'az login' first."
    exit
}
Write-Host "Logged in as $($account.user.name)"

Write-Host "`n1. Creating Azure AD Application '$AppName'..."
$app = az ad app create --display-name $AppName | ConvertFrom-Json
$appId = $app.appId
$objectId = $app.id
Write-Host "App ID: $appId"

Write-Host "`n2. Configuring Microsoft Graph API Permissions..."
# Role IDs for Microsoft Graph Application permissions
$MailSendId = "b633e1c5-b582-4048-a93e-9f11b44c7e96"
$MailReadId = "810c84a8-4a9e-49e6-bf7d-12d59cb20a1c"
$ChatReadWriteId = "21c1fce9-1e5f-4712-bf98-0be8ee4d59a5"
$ChannelMessageSendId = "55a1df47-2c5e-425d-bbd9-a41dc563e46c"
# Delegated permission
$UserReadId = "e1fe6dd8-ba39-4d66-9c7b-990c74fb3904"

# Add permissions
az ad app permission add --id $appId --api $GraphResourceAppId --api-permissions "$MailSendId=Role" "$MailReadId=Role" "$ChatReadWriteId=Role" "$ChannelMessageSendId=Role" "$UserReadId=Scope"

Write-Host "`n3. Granting Admin Consent..."
Write-Host "Attempting admin consent (requires Global Admin privileges)..."
az ad app permission admin-consent --id $appId

Write-Host "`n4. Generating Client Secret..."
$secret = az ad app credential reset --id $appId --append --display-name "BotSecret" --years 2 | ConvertFrom-Json

Write-Host "`n========================================================"
Write-Host "✅ Azure AD Application Created Successfully!"
Write-Host "========================================================"
Write-Host "Keep these credentials safe. Add them to your central backend .env file:`n"
Write-Host "MICROSOFT_APP_ID=$($appId)"
Write-Host "MICROSOFT_APP_PASSWORD=$($secret.password)"
Write-Host "AZURE_TENANT_ID=$($account.tenantId)"
Write-Host "`n========================================================"
Write-Host "NEXT MANUAL STEPS (P2-16 Completion):"
Write-Host "1. Go to the Azure Portal (https://portal.azure.com)"
Write-Host "2. Create a new resource: 'Azure Bot'"
Write-Host "3. For the App Type, select 'Multi Tenant'."
Write-Host "4. For Creation Type, select 'Use existing app registration' and enter the App ID above."
Write-Host "5. Set the Messaging endpoint to your central API: https://<YOUR-API-URL>/integrations/teams/messages"
Write-Host "========================================================"
