"""p1_0002_create_core_error_tables

Revision ID: 059450b37306
Revises: cf19d08c49cc
Create Date: 2026-08-06 09:37:30.458916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '059450b37306'
down_revision: Union[str, Sequence[str], None] = 'cf19d08c49cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobs_code'), 'lobs', ['code'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_evidence_at_severity', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lob_id', 'name', name='uix_category_lob_name')
    )
    op.create_index(op.f('ix_categories_lob_id'), 'categories', ['lob_id'], unique=False)
    op.create_table('sub_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uix_subcategory_category_name')
    )
    op.create_index(op.f('ix_sub_categories_category_id'), 'sub_categories', ['category_id'], unique=False)
    op.create_table('errors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_error_id', sa.String(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=False),
    sa.Column('logged_by_user_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('date_of_occurrence', sa.Date(), nullable=False),
    sa.Column('date_of_detection', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_root_cause', sa.String(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('client_impact_flag', sa.Boolean(), nullable=False),
    sa.Column('sla_rebuttal_window_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('sla_decision_window_hours_snapshot', sa.Integer(), nullable=False),
    sa.Column('sla_clock_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_escalation_level', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name='chk_severity'),
    sa.CheckConstraint('char_length(description) >= 20', name='chk_description_length'),
    sa.CheckConstraint('date_of_occurrence <= CURRENT_DATE', name='chk_date_occurrence'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['lob_id'], ['lobs.id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_errors_created_at', 'errors', ['created_at'], unique=False)
    op.create_index('idx_errors_lob_category', 'errors', ['lob_id', 'category_id'], unique=False)
    op.create_index('idx_errors_owner_user_id', 'errors', ['owner_user_id'], unique=False)
    op.create_index('idx_errors_status', 'errors', ['status'], unique=False)
    op.create_index(op.f('ix_errors_qa_error_id'), 'errors', ['qa_error_id'], unique=True)
    op.create_table('error_status_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('performed_by_system', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_status_history_error_id'), 'error_status_history', ['error_id'], unique=False)
    op.create_index(op.f('ix_error_status_history_occurred_at'), 'error_status_history', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_status_history_occurred_at'), table_name='error_status_history')
    op.drop_index(op.f('ix_error_status_history_error_id'), table_name='error_status_history')
    op.drop_table('error_status_history')
    op.drop_index(op.f('ix_errors_qa_error_id'), table_name='errors')
    op.drop_index('idx_errors_status', table_name='errors')
    op.drop_index('idx_errors_owner_user_id', table_name='errors')
    op.drop_index('idx_errors_lob_category', table_name='errors')
    op.drop_index('idx_errors_created_at', table_name='errors')
    op.drop_table('errors')
    op.drop_index(op.f('ix_sub_categories_category_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    op.drop_index(op.f('ix_categories_lob_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_lobs_code'), table_name='lobs')
    op.drop_table('lobs')
    # ### end Alembic commands ###
