"""Phase 5 models update

Revision ID: 0c3e26e4ebe1
Revises: 76d0fb0a6df8
Create Date: 2026-09-17 05:09:51.701168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3e26e4ebe1'
down_revision: Union[str, None] = '76d0fb0a6df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_events', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.add_column('integration_events', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('integration_events', sa.Column('subscription_id', sa.String(length=255), nullable=True))
    op.add_column('integration_events', sa.Column('external_event_id', sa.String(length=255), nullable=True))
    op.add_column('integration_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('integration_events', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('integration_events', sa.Column('error_info', sa.String(), nullable=True))
    op.create_index(op.f('ix_integration_events_external_event_id'), 'integration_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_integration_events_project_id'), 'integration_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_integration_events_subscription_id'), 'integration_events', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_integration_events_tenant_id'), 'integration_events', ['tenant_id'], unique=False)
    op.add_column('outbox_events', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('locked_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'locked_by')
    op.drop_column('outbox_events', 'locked_at')
    op.drop_index(op.f('ix_integration_events_tenant_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_subscription_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_project_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_external_event_id'), table_name='integration_events')
    op.drop_column('integration_events', 'error_info')
    op.drop_column('integration_events', 'next_attempt_at')
    op.drop_column('integration_events', 'retry_count')
    op.drop_column('integration_events', 'external_event_id')
    op.drop_column('integration_events', 'subscription_id')
    op.drop_column('integration_events', 'project_id')
    op.drop_column('integration_events', 'tenant_id')
    # ### end Alembic commands ###
