"""Add taxonomy_config to Project

Revision ID: 0e8ca6dc4921
Revises: bd2bf9cd4743
Create Date: 2026-09-23 15:46:06.932303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e8ca6dc4921'
down_revision: Union[str, None] = 'bd2bf9cd4743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('taxonomy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'taxonomy_config')
    # ### end Alembic commands ###
