"""Initial Schema Phase 1

Revision ID: 14ef95dc8611
Revises: 
Create Date: 2026-09-16 16:02:47.088300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ef95dc8611'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_resource_mappings',
    sa.Column('internal_entity_type', sa.String(length=100), nullable=False),
    sa.Column('internal_entity_id', sa.String(length=36), nullable=False),
    sa.Column('external_system', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_resource_mappings_external_id'), 'external_resource_mappings', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_resource_mappings_internal_entity_id'), 'external_resource_mappings', ['internal_entity_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_idempotency_key'), 'idempotency_records', ['idempotency_key'], unique=True)
    op.create_table('integration_events',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_idempotency_key'), 'integration_events', ['idempotency_key'], unique=True)
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_idempotency_key'), 'outbox_events', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_outbox_events_project_id'), 'outbox_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_model_configurations',
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_secret_ref', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_configurations_tenant_id'), 'ai_model_configurations', ['tenant_id'], unique=False)
    op.create_table('microsoft_connections',
    sa.Column('entra_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microsoft_connections_tenant_id'), 'microsoft_connections', ['tenant_id'], unique=False)
    op.create_table('microsoft_resource_mappings',
    sa.Column('internal_entity_type', sa.String(length=100), nullable=False),
    sa.Column('internal_entity_id', sa.String(length=36), nullable=False),
    sa.Column('microsoft_resource_id', sa.String(length=255), nullable=False),
    sa.Column('microsoft_resource_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microsoft_resource_mappings_internal_entity_id'), 'microsoft_resource_mappings', ['internal_entity_id'], unique=False)
    op.create_index(op.f('ix_microsoft_resource_mappings_microsoft_resource_id'), 'microsoft_resource_mappings', ['microsoft_resource_id'], unique=False)
    op.create_index(op.f('ix_microsoft_resource_mappings_tenant_id'), 'microsoft_resource_mappings', ['tenant_id'], unique=False)
    op.create_table('microsoft_subscriptions',
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('subscription_id', sa.String(length=255), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id')
    )
    op.create_index(op.f('ix_microsoft_subscriptions_tenant_id'), 'microsoft_subscriptions', ['tenant_id'], unique=False)
    op.create_table('processes',
    sa.Column('quality_category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_processes_tenant_id')
    )
    op.create_index(op.f('ix_processes_quality_category_id'), 'processes', ['quality_category_id'], unique=False)
    op.create_index(op.f('ix_processes_tenant_id'), 'processes', ['tenant_id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('quality_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_quality_categories_tenant_id')
    )
    op.create_index(op.f('ix_quality_categories_tenant_id'), 'quality_categories', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('sops',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sops_tenant_id'), 'sops', ['tenant_id'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entra_id_sub', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_entra_id_sub'), 'users', ['entra_id_sub'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('ai_analysis_runs',
    sa.Column('quality_event_id', sa.String(length=36), nullable=True),
    sa.Column('model_configuration_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=True),
    sa.Column('raw_response', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_configuration_id'], ['ai_model_configurations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_ai_analysis_runs_project_id')
    )
    op.create_index(op.f('ix_ai_analysis_runs_project_id'), 'ai_analysis_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_runs_quality_event_id'), 'ai_analysis_runs', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_runs_tenant_id'), 'ai_analysis_runs', ['tenant_id'], unique=False)
    op.create_table('ai_usage_records',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('model_configuration_id', sa.String(length=36), nullable=False),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['model_configuration_id'], ['ai_model_configurations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_records_tenant_id'), 'ai_usage_records', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('calibration_sessions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_calibration_sessions_project_id')
    )
    op.create_index(op.f('ix_calibration_sessions_process_id'), 'calibration_sessions', ['process_id'], unique=False)
    op.create_index(op.f('ix_calibration_sessions_project_id'), 'calibration_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_calibration_sessions_status'), 'calibration_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_calibration_sessions_tenant_id'), 'calibration_sessions', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('quality_event_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_conversations_project_id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_quality_event_id'), 'conversations', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('teams_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('quality_events',
    sa.Column('event_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('sub_process_id', sa.String(length=36), nullable=False),
    sa.Column('error_type_id', sa.String(length=36), nullable=False),
    sa.Column('sop_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('customer_impact', sa.String(), nullable=False),
    sa.Column('financial_impact', sa.String(), nullable=True),
    sa.Column('compliance_impact', sa.String(), nullable=True),
    sa.Column('expected_outcome', sa.String(), nullable=True),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_quality_events_project_id')
    )
    op.create_index(op.f('ix_quality_events_employee_id'), 'quality_events', ['employee_id'], unique=False)
    op.create_index(op.f('ix_quality_events_event_number'), 'quality_events', ['event_number'], unique=True)
    op.create_index(op.f('ix_quality_events_owner_id'), 'quality_events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_quality_events_process_id'), 'quality_events', ['process_id'], unique=False)
    op.create_index(op.f('ix_quality_events_project_id'), 'quality_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_quality_events_severity'), 'quality_events', ['severity'], unique=False)
    op.create_index(op.f('ix_quality_events_sla_due_at'), 'quality_events', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_quality_events_status'), 'quality_events', ['status'], unique=False)
    op.create_index(op.f('ix_quality_events_team_id'), 'quality_events', ['team_id'], unique=False)
    op.create_index(op.f('ix_quality_events_tenant_id'), 'quality_events', ['tenant_id'], unique=False)
    op.create_table('sla_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('resolution_target_hours', sa.Integer(), nullable=True),
    sa.Column('rebuttal_window_hours', sa.Integer(), nullable=False),
    sa.Column('qa_response_hours', sa.Integer(), nullable=False),
    sa.Column('escalation_window_hours', sa.Integer(), nullable=False),
    sa.Column('warning_threshold_percent', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'process_id'], ['processes.tenant_id', 'processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_policies_process_id'), 'sla_policies', ['process_id'], unique=False)
    op.create_index(op.f('ix_sla_policies_tenant_id'), 'sla_policies', ['tenant_id'], unique=False)
    op.create_table('sub_processes',
    sa.Column('process_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'process_id'], ['processes.tenant_id', 'processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_sub_processes_tenant_id')
    )
    op.create_index(op.f('ix_sub_processes_process_id'), 'sub_processes', ['process_id'], unique=False)
    op.create_index(op.f('ix_sub_processes_tenant_id'), 'sub_processes', ['tenant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('ai_insights',
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('quality_event_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'analysis_run_id'], ['ai_analysis_runs.project_id', 'ai_analysis_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_ai_insights_project_id')
    )
    op.create_index(op.f('ix_ai_insights_analysis_run_id'), 'ai_insights', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_project_id'), 'ai_insights', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_quality_event_id'), 'ai_insights', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_tenant_id'), 'ai_insights', ['tenant_id'], unique=False)
    op.create_table('calibration_cases',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'session_id'], ['calibration_sessions.project_id', 'calibration_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_calibration_cases_project_id')
    )
    op.create_index(op.f('ix_calibration_cases_project_id'), 'calibration_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_calibration_cases_session_id'), 'calibration_cases', ['session_id'], unique=False)
    op.create_index(op.f('ix_calibration_cases_tenant_id'), 'calibration_cases', ['tenant_id'], unique=False)
    op.create_table('calibration_participants',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'session_id'], ['calibration_sessions.project_id', 'calibration_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_calibration_participants_project_id')
    )
    op.create_index(op.f('ix_calibration_participants_project_id'), 'calibration_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_calibration_participants_session_id'), 'calibration_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_calibration_participants_tenant_id'), 'calibration_participants', ['tenant_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'conversation_id'], ['conversations.project_id', 'conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_project_id'), 'conversation_participants', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversation_participants_tenant_id'), 'conversation_participants', ['tenant_id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completion_notes', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_project_id'), 'corrective_actions', ['project_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_quality_event_id'), 'corrective_actions', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_corrective_actions_status'), 'corrective_actions', ['status'], unique=False)
    op.create_index(op.f('ix_corrective_actions_tenant_id'), 'corrective_actions', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('decision_type', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('decided_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_decisions_quality_event_id'), 'decisions', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('effectiveness_reviews',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=False),
    sa.Column('error_rate_before', sa.Float(), nullable=False),
    sa.Column('error_rate_after', sa.Float(), nullable=False),
    sa.Column('recurrence_rate', sa.Float(), nullable=False),
    sa.Column('comparison_period', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quality_event_id')
    )
    op.create_index(op.f('ix_effectiveness_reviews_project_id'), 'effectiveness_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_effectiveness_reviews_tenant_id'), 'effectiveness_reviews', ['tenant_id'], unique=False)
    op.create_table('error_types',
    sa.Column('sub_process_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'sub_process_id'], ['sub_processes.tenant_id', 'sub_processes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_types_sub_process_id'), 'error_types', ['sub_process_id'], unique=False)
    op.create_index(op.f('ix_error_types_tenant_id'), 'error_types', ['tenant_id'], unique=False)
    op.create_table('escalations',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('escalated_by_id', sa.String(length=36), nullable=False),
    sa.Column('escalated_to_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['escalated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['escalated_to_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_project_id'), 'escalations', ['project_id'], unique=False)
    op.create_index(op.f('ix_escalations_quality_event_id'), 'escalations', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_index(op.f('ix_escalations_tenant_id'), 'escalations', ['tenant_id'], unique=False)
    op.create_table('evidence',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('highlight_timestamp', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_quality_event_id'), 'evidence', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_evidence_tenant_id'), 'evidence', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'conversation_id'], ['conversations.project_id', 'conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_messages_project_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_table('rebuttals',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('qa_assessed_by_id', sa.String(length=36), nullable=True),
    sa.Column('qa_decision', sa.String(length=50), nullable=True),
    sa.Column('qa_rationale', sa.String(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qa_assessed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_rebuttals_project_id'),
    sa.UniqueConstraint('quality_event_id')
    )
    op.create_index(op.f('ix_rebuttals_project_id'), 'rebuttals', ['project_id'], unique=False)
    op.create_index(op.f('ix_rebuttals_status'), 'rebuttals', ['status'], unique=False)
    op.create_index(op.f('ix_rebuttals_tenant_id'), 'rebuttals', ['tenant_id'], unique=False)
    op.create_table('root_causes',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('problem_statement', sa.String(), nullable=True),
    sa.Column('five_whys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fishbone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=False),
    sa.Column('contributing_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('completed_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id', name='uq_root_causes_project_id'),
    sa.UniqueConstraint('quality_event_id')
    )
    op.create_index(op.f('ix_root_causes_project_id'), 'root_causes', ['project_id'], unique=False)
    op.create_index(op.f('ix_root_causes_tenant_id'), 'root_causes', ['tenant_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_quality_event_id'), 'timeline_events', ['quality_event_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_tenant_id'), 'timeline_events', ['tenant_id'], unique=False)
    op.create_table('ai_insight_feedback',
    sa.Column('insight_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'insight_id'], ['ai_insights.project_id', 'ai_insights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insight_feedback_insight_id'), 'ai_insight_feedback', ['insight_id'], unique=False)
    op.create_index(op.f('ix_ai_insight_feedback_project_id'), 'ai_insight_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_insight_feedback_tenant_id'), 'ai_insight_feedback', ['tenant_id'], unique=False)
    op.create_table('calibration_evaluations',
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'case_id'], ['calibration_cases.project_id', 'calibration_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id', 'participant_id'], ['calibration_participants.project_id', 'calibration_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_evaluations_participant_id'), 'calibration_evaluations', ['participant_id'], unique=False)
    op.create_index(op.f('ix_calibration_evaluations_project_id'), 'calibration_evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_calibration_evaluations_tenant_id'), 'calibration_evaluations', ['tenant_id'], unique=False)
    op.create_table('calibration_variances',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('score_variance', sa.Float(), nullable=True),
    sa.Column('final_calibrated_score', sa.Float(), nullable=True),
    sa.Column('decision_rationale', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'case_id'], ['calibration_cases.project_id', 'calibration_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_calibration_variances_project_id'), 'calibration_variances', ['project_id'], unique=False)
    op.create_index(op.f('ix_calibration_variances_tenant_id'), 'calibration_variances', ['tenant_id'], unique=False)
    op.create_table('contributing_factors',
    sa.Column('root_cause_id', sa.String(length=36), nullable=False),
    sa.Column('factor_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'root_cause_id'], ['root_causes.project_id', 'root_causes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributing_factors_project_id'), 'contributing_factors', ['project_id'], unique=False)
    op.create_index(op.f('ix_contributing_factors_root_cause_id'), 'contributing_factors', ['root_cause_id'], unique=False)
    op.create_index(op.f('ix_contributing_factors_tenant_id'), 'contributing_factors', ['tenant_id'], unique=False)
    op.create_table('discussion_threads',
    sa.Column('rebuttal_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'rebuttal_id'], ['rebuttals.project_id', 'rebuttals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_threads_project_id'), 'discussion_threads', ['project_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_rebuttal_id'), 'discussion_threads', ['rebuttal_id'], unique=False)
    op.create_index(op.f('ix_discussion_threads_tenant_id'), 'discussion_threads', ['tenant_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'message_id'], ['messages.project_id', 'messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_project_id'), 'message_attachments', ['project_id'], unique=False)
    op.create_index(op.f('ix_message_attachments_tenant_id'), 'message_attachments', ['tenant_id'], unique=False)
    op.create_table('message_read_states',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'message_id'], ['messages.project_id', 'messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_read_states_message_id'), 'message_read_states', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_read_states_project_id'), 'message_read_states', ['project_id'], unique=False)
    op.create_index(op.f('ix_message_read_states_tenant_id'), 'message_read_states', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_read_states_tenant_id'), table_name='message_read_states')
    op.drop_index(op.f('ix_message_read_states_project_id'), table_name='message_read_states')
    op.drop_index(op.f('ix_message_read_states_message_id'), table_name='message_read_states')
    op.drop_table('message_read_states')
    op.drop_index(op.f('ix_message_attachments_tenant_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_project_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_discussion_threads_tenant_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_rebuttal_id'), table_name='discussion_threads')
    op.drop_index(op.f('ix_discussion_threads_project_id'), table_name='discussion_threads')
    op.drop_table('discussion_threads')
    op.drop_index(op.f('ix_contributing_factors_tenant_id'), table_name='contributing_factors')
    op.drop_index(op.f('ix_contributing_factors_root_cause_id'), table_name='contributing_factors')
    op.drop_index(op.f('ix_contributing_factors_project_id'), table_name='contributing_factors')
    op.drop_table('contributing_factors')
    op.drop_index(op.f('ix_calibration_variances_tenant_id'), table_name='calibration_variances')
    op.drop_index(op.f('ix_calibration_variances_project_id'), table_name='calibration_variances')
    op.drop_table('calibration_variances')
    op.drop_index(op.f('ix_calibration_evaluations_tenant_id'), table_name='calibration_evaluations')
    op.drop_index(op.f('ix_calibration_evaluations_project_id'), table_name='calibration_evaluations')
    op.drop_index(op.f('ix_calibration_evaluations_participant_id'), table_name='calibration_evaluations')
    op.drop_table('calibration_evaluations')
    op.drop_index(op.f('ix_ai_insight_feedback_tenant_id'), table_name='ai_insight_feedback')
    op.drop_index(op.f('ix_ai_insight_feedback_project_id'), table_name='ai_insight_feedback')
    op.drop_index(op.f('ix_ai_insight_feedback_insight_id'), table_name='ai_insight_feedback')
    op.drop_table('ai_insight_feedback')
    op.drop_index(op.f('ix_timeline_events_tenant_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_quality_event_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_root_causes_tenant_id'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_project_id'), table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_rebuttals_tenant_id'), table_name='rebuttals')
    op.drop_index(op.f('ix_rebuttals_status'), table_name='rebuttals')
    op.drop_index(op.f('ix_rebuttals_project_id'), table_name='rebuttals')
    op.drop_table('rebuttals')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evidence_tenant_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_quality_event_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_escalations_tenant_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_quality_event_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_project_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_error_types_tenant_id'), table_name='error_types')
    op.drop_index(op.f('ix_error_types_sub_process_id'), table_name='error_types')
    op.drop_table('error_types')
    op.drop_index(op.f('ix_effectiveness_reviews_tenant_id'), table_name='effectiveness_reviews')
    op.drop_index(op.f('ix_effectiveness_reviews_project_id'), table_name='effectiveness_reviews')
    op.drop_table('effectiveness_reviews')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_quality_event_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_corrective_actions_tenant_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_status'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_quality_event_id'), table_name='corrective_actions')
    op.drop_index(op.f('ix_corrective_actions_project_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_conversation_participants_tenant_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_project_id'), table_name='conversation_participants')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_calibration_participants_tenant_id'), table_name='calibration_participants')
    op.drop_index(op.f('ix_calibration_participants_session_id'), table_name='calibration_participants')
    op.drop_index(op.f('ix_calibration_participants_project_id'), table_name='calibration_participants')
    op.drop_table('calibration_participants')
    op.drop_index(op.f('ix_calibration_cases_tenant_id'), table_name='calibration_cases')
    op.drop_index(op.f('ix_calibration_cases_session_id'), table_name='calibration_cases')
    op.drop_index(op.f('ix_calibration_cases_project_id'), table_name='calibration_cases')
    op.drop_table('calibration_cases')
    op.drop_index(op.f('ix_ai_insights_tenant_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_quality_event_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_project_id'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_analysis_run_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sub_processes_tenant_id'), table_name='sub_processes')
    op.drop_index(op.f('ix_sub_processes_process_id'), table_name='sub_processes')
    op.drop_table('sub_processes')
    op.drop_index(op.f('ix_sla_policies_tenant_id'), table_name='sla_policies')
    op.drop_index(op.f('ix_sla_policies_process_id'), table_name='sla_policies')
    op.drop_table('sla_policies')
    op.drop_index(op.f('ix_quality_events_tenant_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_team_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_status'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_sla_due_at'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_severity'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_project_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_process_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_owner_id'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_event_number'), table_name='quality_events')
    op.drop_index(op.f('ix_quality_events_employee_id'), table_name='quality_events')
    op.drop_table('quality_events')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_quality_event_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_calibration_sessions_tenant_id'), table_name='calibration_sessions')
    op.drop_index(op.f('ix_calibration_sessions_status'), table_name='calibration_sessions')
    op.drop_index(op.f('ix_calibration_sessions_project_id'), table_name='calibration_sessions')
    op.drop_index(op.f('ix_calibration_sessions_process_id'), table_name='calibration_sessions')
    op.drop_table('calibration_sessions')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_ai_usage_records_tenant_id'), table_name='ai_usage_records')
    op.drop_table('ai_usage_records')
    op.drop_index(op.f('ix_ai_analysis_runs_tenant_id'), table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_quality_event_id'), table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_project_id'), table_name='ai_analysis_runs')
    op.drop_table('ai_analysis_runs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_entra_id_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sops_tenant_id'), table_name='sops')
    op.drop_table('sops')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_quality_categories_tenant_id'), table_name='quality_categories')
    op.drop_table('quality_categories')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_processes_tenant_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_quality_category_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_microsoft_subscriptions_tenant_id'), table_name='microsoft_subscriptions')
    op.drop_table('microsoft_subscriptions')
    op.drop_index(op.f('ix_microsoft_resource_mappings_tenant_id'), table_name='microsoft_resource_mappings')
    op.drop_index(op.f('ix_microsoft_resource_mappings_microsoft_resource_id'), table_name='microsoft_resource_mappings')
    op.drop_index(op.f('ix_microsoft_resource_mappings_internal_entity_id'), table_name='microsoft_resource_mappings')
    op.drop_table('microsoft_resource_mappings')
    op.drop_index(op.f('ix_microsoft_connections_tenant_id'), table_name='microsoft_connections')
    op.drop_table('microsoft_connections')
    op.drop_index(op.f('ix_ai_model_configurations_tenant_id'), table_name='ai_model_configurations')
    op.drop_table('ai_model_configurations')
    op.drop_table('tenants')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_project_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_idempotency_key'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_integration_events_idempotency_key'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_idempotency_records_idempotency_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_external_resource_mappings_internal_entity_id'), table_name='external_resource_mappings')
    op.drop_index(op.f('ix_external_resource_mappings_external_id'), table_name='external_resource_mappings')
    op.drop_table('external_resource_mappings')
    # ### end Alembic commands ###
