"""Add sla_status to quality_events

Revision ID: 4947705df422
Revises: 0c3e26e4ebe1
Create Date: 2026-09-17 05:12:30.833537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4947705df422'
down_revision: Union[str, None] = '0c3e26e4ebe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quality_events', sa.Column('sla_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quality_events', 'sla_status')
    # ### end Alembic commands ###
