"""Add request_hash to idempotency

Revision ID: 4a189e9883de
Revises: 4947705df422
Create Date: 2026-09-18 15:25:58.778882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a189e9883de'
down_revision: Union[str, None] = '4947705df422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_records', sa.Column('request_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotency_records', 'request_hash')
    # ### end Alembic commands ###
