"""add_checksum_to_evidence

Revision ID: 76d0fb0a6df8
Revises: 8218b5c512da
Create Date: 2026-09-17 04:37:19.680240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d0fb0a6df8'
down_revision: Union[str, None] = '8218b5c512da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence', sa.Column('checksum', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence', 'checksum')
    # ### end Alembic commands ###
