"""Phase_4_AI_and_Evidence_models

Revision ID: 8218b5c512da
Revises: c0fcc7fd4106
Create Date: 2026-09-16 19:49:00.763162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8218b5c512da'
down_revision: Union[str, None] = 'c0fcc7fd4106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis_runs', sa.Column('event_version', sa.Integer(), nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('analysis_type', sa.String(length=100), nullable=False))
    op.add_column('ai_analysis_runs', sa.Column('provider', sa.String(length=100), nullable=False))
    op.add_column('ai_analysis_runs', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('ai_analysis_runs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('error_info', sa.String(), nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_ai_analysis_runs_idempotency_key'), 'ai_analysis_runs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_ai_analysis_runs_status'), 'ai_analysis_runs', ['status'], unique=False)
    op.drop_constraint(op.f('ai_analysis_runs_model_configuration_id_fkey'), 'ai_analysis_runs', type_='foreignkey')
    op.drop_column('ai_analysis_runs', 'prompt_template')
    op.drop_column('ai_analysis_runs', 'model_configuration_id')
    op.drop_column('ai_analysis_runs', 'raw_response')
    op.add_column('ai_insights', sa.Column('insight_type', sa.String(length=100), nullable=False))
    op.add_column('ai_insights', sa.Column('model_provider', sa.String(length=100), nullable=False))
    op.add_column('ai_insights', sa.Column('model_name', sa.String(length=100), nullable=False))
    op.add_column('ai_insights', sa.Column('prompt_identifier', sa.String(length=100), nullable=True))
    op.add_column('ai_insights', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('ai_insights', sa.Column('rationale', sa.String(), nullable=True))
    op.add_column('ai_insights', sa.Column('created_by_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_ai_insights_created_by_id', 'ai_insights', 'users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('ai_insights', 'summary')
    op.drop_column('ai_insights', 'type')
    op.drop_column('ai_insights', 'recommendation')
    op.add_column('ai_usage_records', sa.Column('analysis_run_id', sa.String(length=36), nullable=True))
    op.add_column('ai_usage_records', sa.Column('provider', sa.String(length=100), nullable=False))
    op.add_column('ai_usage_records', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('ai_usage_records', sa.Column('input_tokens', sa.Integer(), nullable=False))
    op.add_column('ai_usage_records', sa.Column('output_tokens', sa.Integer(), nullable=False))
    op.add_column('ai_usage_records', sa.Column('estimated_cost', sa.String(length=50), nullable=True))
    op.add_column('ai_usage_records', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_usage_records_analysis_run_id'), 'ai_usage_records', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_records_project_id'), 'ai_usage_records', ['project_id'], unique=False)
    op.drop_constraint(op.f('ai_usage_records_model_configuration_id_fkey'), 'ai_usage_records', type_='foreignkey')
    op.create_foreign_key('fk_ai_usage_records_analysis_run_id', 'ai_usage_records', 'ai_analysis_runs', ['analysis_run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ai_usage_records', 'tokens_completion')
    op.drop_column('ai_usage_records', 'tokens_prompt')
    op.drop_column('ai_usage_records', 'model_configuration_id')
    op.drop_column('ai_usage_records', 'cost_estimate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_records', sa.Column('cost_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('ai_usage_records', sa.Column('model_configuration_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('ai_usage_records', sa.Column('tokens_prompt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_usage_records', sa.Column('tokens_completion', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_ai_usage_records_analysis_run_id', 'ai_usage_records', type_='foreignkey')
    op.create_foreign_key(op.f('ai_usage_records_model_configuration_id_fkey'), 'ai_usage_records', 'ai_model_configurations', ['model_configuration_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_ai_usage_records_project_id'), table_name='ai_usage_records')
    op.drop_index(op.f('ix_ai_usage_records_analysis_run_id'), table_name='ai_usage_records')
    op.drop_column('ai_usage_records', 'duration_ms')
    op.drop_column('ai_usage_records', 'estimated_cost')
    op.drop_column('ai_usage_records', 'output_tokens')
    op.drop_column('ai_usage_records', 'input_tokens')
    op.drop_column('ai_usage_records', 'model')
    op.drop_column('ai_usage_records', 'provider')
    op.drop_column('ai_usage_records', 'analysis_run_id')
    op.add_column('ai_insights', sa.Column('recommendation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_insights', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('ai_insights', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_ai_insights_created_by_id', 'ai_insights', type_='foreignkey')
    op.drop_column('ai_insights', 'created_by_id')
    op.drop_column('ai_insights', 'rationale')
    op.drop_column('ai_insights', 'result')
    op.drop_column('ai_insights', 'prompt_identifier')
    op.drop_column('ai_insights', 'model_name')
    op.drop_column('ai_insights', 'model_provider')
    op.drop_column('ai_insights', 'insight_type')
    op.add_column('ai_analysis_runs', sa.Column('raw_response', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_analysis_runs', sa.Column('model_configuration_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('ai_analysis_runs', sa.Column('prompt_template', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ai_analysis_runs_model_configuration_id_fkey'), 'ai_analysis_runs', 'ai_model_configurations', ['model_configuration_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_ai_analysis_runs_status'), table_name='ai_analysis_runs')
    op.drop_index(op.f('ix_ai_analysis_runs_idempotency_key'), table_name='ai_analysis_runs')
    op.drop_column('ai_analysis_runs', 'idempotency_key')
    op.drop_column('ai_analysis_runs', 'request_id')
    op.drop_column('ai_analysis_runs', 'error_info')
    op.drop_column('ai_analysis_runs', 'completed_at')
    op.drop_column('ai_analysis_runs', 'started_at')
    op.drop_column('ai_analysis_runs', 'model')
    op.drop_column('ai_analysis_runs', 'provider')
    op.drop_column('ai_analysis_runs', 'analysis_type')
    op.drop_column('ai_analysis_runs', 'event_version')
    # ### end Alembic commands ###
