"""add working hours

Revision ID: 9627c947f968
Revises: e2cf7efd2aaf
Create Date: 2026-08-29 21:55:16.522645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9627c947f968'
down_revision: Union[str, Sequence[str], None] = 'e2cf7efd2aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_hours_calendar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('business_start_time', sa.Time(), nullable=False),
    sa.Column('business_end_time', sa.Time(), nullable=False),
    sa.Column('business_days_of_week', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_hours_calendar_region_code'), 'working_hours_calendar', ['region_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_hours_calendar_region_code'), table_name='working_hours_calendar')
    op.drop_table('working_hours_calendar')
    # ### end Alembic commands ###
