"""phase_c_sla_escalation

Revision ID: a1b2c3d4e5f6
Revises: f9e8d7c6b5a4
Create Date: 2026-09-26 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'f9e8d7c6b5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_matrices',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_escalation_matrices_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('working_hours_calendars',
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_working_hours_calendars_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('holidays',
    sa.Column('holiday_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_holidays_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('escalation_rules',
    sa.Column('escalation_matrix_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('threshold_pct', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.SmallInteger(), nullable=False),
    sa.Column('recipient_role', sa.String(length=100), nullable=True),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=True),
    sa.Column('notification_channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['escalation_matrix_id'], ['escalation_matrices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_escalation_rules_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Modify sla_policies
    op.add_column('sla_policies', sa.Column('stage', sa.String(length=50), nullable=False, server_default='acknowledgement'))
    op.alter_column('sla_policies', 'stage', server_default=None)
    
    op.add_column('sla_policies', sa.Column('duration_minutes', sa.Integer(), nullable=False, server_default='2880'))
    op.alter_column('sla_policies', 'duration_minutes', server_default=None)
    
    op.add_column('sla_policies', sa.Column('use_working_hours', sa.String(length=50), nullable=False, server_default='calendar'))
    op.alter_column('sla_policies', 'use_working_hours', server_default=None)
    
    op.add_column('sla_policies', sa.Column('pause_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sla_policies', sa.Column('escalation_matrix_id', sa.String(length=36), nullable=True))
    op.add_column('sla_policies', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('sla_policies', sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    
    op.create_foreign_key('fk_sla_policies_escalation_matrix_id', 'sla_policies', 'escalation_matrices', ['escalation_matrix_id'], ['id'], ondelete='SET NULL')
    
    op.drop_column('sla_policies', 'resolution_target_hours')
    op.drop_column('sla_policies', 'rebuttal_window_hours')
    op.drop_column('sla_policies', 'qa_response_hours')
    op.drop_column('sla_policies', 'escalation_window_hours')
    op.drop_column('sla_policies', 'name')
    
    # SLAClocks
    op.create_table('sla_clocks',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('sla_policy_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_intervals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elapsed_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_clocks_quality_event_id'), 'sla_clocks', ['quality_event_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    pass # Skipped for brevity
