"""Add entra_tenant_id to Tenant

Revision ID: c0fcc7fd4106
Revises: 14ef95dc8611
Create Date: 2026-09-16 18:14:05.941543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fcc7fd4106'
down_revision: Union[str, None] = '14ef95dc8611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('entra_tenant_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_entra_tenant_id'), 'tenants', ['entra_tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_entra_tenant_id'), table_name='tenants')
    op.drop_column('tenants', 'entra_tenant_id')
    # ### end Alembic commands ###
