"""p2_0001_create_rebuttals_decisions

Revision ID: c19cfc2e888a
Revises: d1ff77d5c188
Create Date: 2026-08-06 22:00:54.634915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19cfc2e888a'
down_revision: Union[str, Sequence[str], None] = 'd1ff77d5c188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('partial_breakdown', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("decision IN ('UPHELD','OVERTURNED','PARTIALLY_UPHELD')", name='decision_enum'),
    sa.CheckConstraint('length(rationale) >= 20', name='rationale_min_length'),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rebuttals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('evidence_file_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('length(justification) >= 20', name='justification_min_length'),
    sa.ForeignKeyConstraint(['error_id'], ['errors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebuttals')
    op.drop_table('decisions')
    # ### end Alembic commands ###
