"""p1_0003_qa_error_sequence

Revision ID: d1ff77d5c188
Revises: 059450b37306
Create Date: 2026-08-06 10:33:33.448303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ff77d5c188'
down_revision: Union[str, Sequence[str], None] = '059450b37306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_error_id_sequences',
    sa.Column('lob_year_key', sa.String(), nullable=False),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('lob_year_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_error_id_sequences')
    # ### end Alembic commands ###
