"""p3_0006_evidence_rules

Revision ID: d76855e80f52
Revises: b84266bcd803
Create Date: 2026-08-28 14:56:51.467402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76855e80f52'
down_revision: Union[str, Sequence[str], None] = 'b84266bcd803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('max_file_count_per_error', sa.Integer(), nullable=False),
    sa.Column('allowed_file_types', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_rules')
    # ### end Alembic commands ###
