"""phase_a_sync_history_logs

Revision ID: d9f1b2c3a4e5
Revises: 0e8ca6dc4921
Create Date: 2026-09-26 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9f1b2c3a4e5'
down_revision: Union[str, None] = '0e8ca6dc4921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_history_logs',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('superseded_local_version', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('server_winning_version', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflict_reason', sa.String(), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_sync_history_logs_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_history_logs_entity_id'), 'sync_history_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sync_history_logs_project_id'), 'sync_history_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_sync_history_logs_tenant_id'), 'sync_history_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_history_logs_tenant_id'), table_name='sync_history_logs')
    op.drop_index(op.f('ix_sync_history_logs_project_id'), table_name='sync_history_logs')
    op.drop_index(op.f('ix_sync_history_logs_entity_id'), table_name='sync_history_logs')
    op.drop_table('sync_history_logs')
    # ### end Alembic commands ###
