"""add holidays

Revision ID: e2cf7efd2aaf
Revises: d76855e80f52
Create Date: 2026-08-29 11:50:50.250501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2cf7efd2aaf'
down_revision: Union[str, Sequence[str], None] = 'd76855e80f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_change_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_change_history_changed_at'), 'config_change_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_config_change_history_config_entity'), 'config_change_history', ['config_entity'], unique=False)
    op.create_index(op.f('ix_config_change_history_entity_id'), 'config_change_history', ['entity_id'], unique=False)
    op.create_table('escalation_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('threshold_hours_after_breach', sa.Integer(), nullable=False),
    sa.Column('recipient_role_id', sa.UUID(), nullable=True),
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_matrix_is_active'), 'escalation_matrix', ['is_active'], unique=False)
    op.create_index(op.f('ix_escalation_matrix_lob_id'), 'escalation_matrix', ['lob_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_region_code'), 'holidays', ['region_code'], unique=False)
    op.create_table('ownership_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('default_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('default_owner_team_ref', sa.UUID(), nullable=True),
    sa.Column('default_owner_manager_user_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_mapping_category_id'), 'ownership_mapping', ['category_id'], unique=False)
    op.create_index(op.f('ix_ownership_mapping_effective_to'), 'ownership_mapping', ['effective_to'], unique=False)
    op.create_index(op.f('ix_ownership_mapping_lob_id'), 'ownership_mapping', ['lob_id'], unique=False)
    op.create_table('sla_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('rebuttal_window_hours', sa.Integer(), nullable=False),
    sa.Column('decision_window_hours', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_rules_category_id'), 'sla_rules', ['category_id'], unique=False)
    op.create_index(op.f('ix_sla_rules_effective_to'), 'sla_rules', ['effective_to'], unique=False)
    op.create_index(op.f('ix_sla_rules_lob_id'), 'sla_rules', ['lob_id'], unique=False)
    op.create_index(op.f('ix_sla_rules_severity'), 'sla_rules', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_rules_severity'), table_name='sla_rules')
    op.drop_index(op.f('ix_sla_rules_lob_id'), table_name='sla_rules')
    op.drop_index(op.f('ix_sla_rules_effective_to'), table_name='sla_rules')
    op.drop_index(op.f('ix_sla_rules_category_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_index(op.f('ix_ownership_mapping_lob_id'), table_name='ownership_mapping')
    op.drop_index(op.f('ix_ownership_mapping_effective_to'), table_name='ownership_mapping')
    op.drop_index(op.f('ix_ownership_mapping_category_id'), table_name='ownership_mapping')
    op.drop_table('ownership_mapping')
    op.drop_index(op.f('ix_holidays_region_code'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_escalation_matrix_lob_id'), table_name='escalation_matrix')
    op.drop_index(op.f('ix_escalation_matrix_is_active'), table_name='escalation_matrix')
    op.drop_table('escalation_matrix')
    op.drop_index(op.f('ix_config_change_history_entity_id'), table_name='config_change_history')
    op.drop_index(op.f('ix_config_change_history_config_entity'), table_name='config_change_history')
    op.drop_index(op.f('ix_config_change_history_changed_at'), table_name='config_change_history')
    op.drop_table('config_change_history')
    # ### end Alembic commands ###
