"""phase_b_decision_reopen

Revision ID: e8c9d0f1a2b3
Revises: d9f1b2c3a4e5
Create Date: 2026-09-26 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e8c9d0f1a2b3'
down_revision: Union[str, None] = 'd9f1b2c3a4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reopen_events',
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('quality_event_id', sa.String(length=36), nullable=False),
    sa.Column('reopened_by_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'quality_event_id'], ['quality_events.project_id', 'quality_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reopened_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reopen_events_project_id'), 'reopen_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_reopen_events_quality_event_id'), 'reopen_events', ['quality_event_id'], unique=False)
    
    op.add_column('decisions', sa.Column('requires_capa', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('decisions', sa.Column('requires_capa_override_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'requires_capa_override_reason')
    op.drop_column('decisions', 'requires_capa')
    
    op.drop_index(op.f('ix_reopen_events_quality_event_id'), table_name='reopen_events')
    op.drop_index(op.f('ix_reopen_events_project_id'), table_name='reopen_events')
    op.drop_table('reopen_events')
    # ### end Alembic commands ###
